name: "build and publish jekyll site"
on:
  push:
  workflow_call:
jobs:
  buildandpublish:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/ubuntu:questing
      options: '--user=root'
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/jekyll-build-pages@v1
        with:
          destination: './_site/techdiary'
        env:
          TZ: Asia/Kolkata
      - name: setup redirect
        working-directory: /home/runner/work/techdiary/techdiary/_site
        run: cp ../redirect.html index.html

      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v5
